### ISSUE TITLE
cache wordpress admin wp-admin

### ISSUE THREAD

**Issue by mxmkmarquette** [davinder17s/easy-gzip-cache#1]
very nice script but it cache wordpress admin.

**Comment by davinder17s** [comment]
Thanks, this script is made to reduce the burden of caching static files,
like css, js, png, jpg, because when you design, there are lot of files,
which reduce page loading speed.
But you can use gzip code to reduce the size of response

**Comment by mxmkmarquette** [comment]
yes i know that but it should not cache wp-admin is there a way to take advantage of this but not make it cache wp-admin cause it break the wp-admin then.

`Uncaught SyntaxError: Unexpected token <`

i got that from gzip.php in my wp-admin.

**Comment by davinder17s** [comment]
Well, i guess you have not used .htaccess rewrite correctly

**Comment by davinder17s** [comment]
Please check example .htaccess in repository
